### PR TITLE
psuedocode and notes for completing processing time remaining

### PR DESCRIPTION
**Pull request by mayeaux**

### CODE REVIEW

**Comment by Mxchaeltrxn** [comment]
Wait this isn't done

**Comment by Mxchaeltrxn** [comment]
During merge from master, I changed `normalNetworkTimeoutInSeconds` from 2.5 to 3 so that it works with the setIntervalX function . I don't know how significant that is or if you want to change it to 2 instead or use a different solution.

**Comment by mayeaux** [comment]
> During merge from master, I changed `normalNetworkTimeoutInSeconds` from 2.5 to 3 so that it works with the setIntervalX function . I don't know how significant that is or if you want to change it to 2 instead or use a different solution.

It should be fine. The one thing I would note though is try and leave some comments explaining in English what certain functions are doing. For example: 

views/mediaPlayerPartials/progressTrackerJs.pug:60 (setIntervalX) 

I can kind of see what you're getting at but a nice comment at the top just explaining the design and what it hopes to achieve will help me and others 1000x more than trying to divine the meaning of code. There is a good quote that 1 line of comment is worth 5 lines of code (I think that was the ratio) and it's totally true lol a good English language explanation of what's going on is worth its weight in gold.

**Comment by mayeaux** [comment]
Also controllers/frontend/account.js:69, do we still need throttle passed to the frontend? I can't see it being used anymore

**Comment by mayeaux** [comment]
I'm merging this, I noticed a bug in the processing page where if you refresh the page the logic is off, so we'll need to take a look at that. The uploading functionality works great though so I'll merge that in the meantime, we can take a look at that in a bit.

**Pull request merged**
