### PR TITLE
Create a separate license file

### PR DESCRIPTION
**Pull request by zdroid**
This way, GitHub will automatically recognize the license. It also makes the license easier to be noticed by potential contributors.

### CODE REVIEW

**Comment by mayeaux** [comment]
Thanks @zdroid for getting this started. Actually a collaborator and myself have been discussing it and I'm leaning towards making the project AGPL licensed, what's your take on that? And I promise moving the license into its separate file is on my to-do list it's just below a bunch of stuff so thank you for getting the ball rolling on that!

**Comment by zdroid** [comment]
It depends on what do you want the project to become. AGPL has a lot of conditions to potential forks. MIT has only one (License and copyright notice), on the other side.

**Comment by mayeaux** [comment]
I like the idea that a company wouldn't be able to fork the code, improve it and then license it without a licensing agreement, really I want to model this project after WordPress and they run a GPLv2+ license, but I think the additional clause of AGPL could be useful based upon the kind of service NodeTube is (distributed servers). So that was my thought process, I think I will merge this here just so it's cleaner and also automatically recognized by Github but I think a move to AGPL may be in the future. Thanks for the PR!

**Comment by zdroid** [comment]
You're right, that's one way to go. There's also a blogging service licensed under MIT, [Ghost](https://github.com/TryGhost/Ghost/blob/master/LICENSE).

**Comment by mayeaux** [comment]
Oh cool, Ghost uses the MIT license. What do you think would be best for the community at large? I had one collaborator telling me he flatly refuses to work on anything as OS that isn't GPL licensed lol. Luckily from MIT I can switch to GPL so we have some time on our hands here to hash it out and make a solid decision.

**Comment by zdroid** [comment]
GPL is better for business, MIT for the community. Almost all popular GitHub projects (with really large communities) use MIT.

**Comment by mayeaux** [comment]
Thanks for that info, I'd definitely like to hear more from the community on their opinion as well but thanks for the PR man you're epic!

**Pull request merged**
