### PR TITLE
fix docker.

### PR DESCRIPTION
**Pull request by chovy**

### CODE REVIEW

**Comment by RossComputerGuy** [comment]
I suggest adding a line to the Dockerfile: `USER node`. This sets the user to the `node` user which exists in the Node.JS Docker images. The permissions will also be correct when trying to access data which I think people would like having that fixed. That also means no need to use `sudo chown`.

**Comment by chovy** [comment]
> I suggest adding a line to the Dockerfile: `USER node`. This sets the user to the `node` user which exists in the Node.JS Docker images. The permissions will also be correct when trying to access data which I think people would like having that fixed. That also means no need to use `sudo chown`.

docker user is root by default. all files are owned by root.

**Comment by RossComputerGuy** [comment]
Yeah but it'll be better to have the container run as `node`. Then `sudo` is not required, less of a hassle.

**Comment by chovy** [comment]
> Yeah but it'll be better to have the container run as `node`. Then `sudo` is not required, less of a hassle.

done. i haven't tested so i'm trust it works. I will try next time I deploy.

**Comment by RossComputerGuy** [comment]
Yeah, I've noticed mongo might own the database files with UID being 999. Might need to look into fixing that.

**Pull request merged**
