### PR TITLE
Fixing vulnerabilities

### PR DESCRIPTION
**Pull request by RossComputerGuy**
Node also said this:
```
fixed 2 of 7 vulnerabilities in 9548 scanned packages
  2 vulnerabilities required manual review and could not be updated
  2 package updates for 3 vulnerabilities involved breaking changes
```

### CODE REVIEW

**Comment by RossComputerGuy** [comment]
Packages that are listed under manual review:
* `https-proxy-agen`: DoS and MITM
* `mongodb`: DoS
* `growl`: Command injection
* `debug`: Regular expression DoS

**Comment by RossComputerGuy** [comment]
All dependencies have been updated

**Comment by RossComputerGuy** [comment]
I tested it in Docker, everything works.

**Comment by mayeaux** [comment]
Thanks a lot, great work!

**Pull request merged**
